vm: print which file is missing in one case
    adb shell /apex/com.android.virt/bin/vm run-app non-existant.apk foo bar
    Error: No such file or directory (os error 2)

=>

    adb shell /apex/com.android.virt/bin/vm run-app non-existant.apk foo bar
    Error: Failed to open APK file

    Caused by:
        No such file or directory (os error 2)

Bug: N/A
Test: manual
Change-Id: I14264ed5d978b3998c183bb5729ca47ca2b39426